import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
 
// These styles apply to every route in the application
import './globals.css'
import { text } from 'stream/consumers'
import product from './@product/page'
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,product
}: {
  children: React.ReactNode
  product: React.ReactNode
}

) {
  return (
    <html lang="en">
      <body>
        {/* // ======================================================== */}
        
        {/* ================================================================== */}
        
        
        
        {children}, {product}
      
      <Image
          src="/image-home/header1.jpg" // Route of the image file
          height={50} // Desired size with correct aspect ratio
          width={1200} // Desired size with correct aspect ratio
          alt="Homeo"
        />
        <div className="footermenu">
        <h2 className="text-2xl font-extrabold dark:text-white">
        <p> &ensp; &ensp;</p>
            <Link  href="/">Home </Link>
            <Link href="/about">| About </Link>
            <Link href="/contact">  | Contact</Link>
            <p> &ensp; &ensp;</p>
        </h2>
      </div>
      </body>
    </html>
  )
}