import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
 
// These styles apply to every route in the application
import './globals.css'
import { text } from 'stream/consumers'
import product from './@product/page'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children, names
}: {
  children: React.ReactNode
  names: React.ReactNode
}

) {
  return (
    <html lang="en">
      <body>
        {/* Buttons - Menue -Start */}

        <div className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-left mr-2 mb-2">
        
        <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link  href="/">Home</Link>
          </button>
          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/medicines">Homeo Medicines</Link>
          </button>

          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/about">About</Link>
          </button>
          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/contact">Contact</Link>
          </button>

      <Image className="w-32 h-32 rounded-full shadow-2xl dark:shadow-green-800 float-right"
          src="/image-home/logo.jpg" // Route of the image file
          height={50} // Desired size with correct aspect ratio
          width={1200} // Desired size with correct aspect ratio
          alt="Homeo"
        />
 
        </div>
{/* Buttons - Menue -End */}
        
<Image className="max-w-xl h-auto float-right mx-auto rounded-full shadow-2xl dark:shadow-green-800"
          src="/image-home/header2.jpg" //. Route of the image file
          height={50} // Desired size with correct aspect ratio
          width={1200} // Desired size with correct aspect ratio
          alt="Homeo"
        />
        
          {children}, {names}
      
      <Image className="max-w-xl h-auto mx-auto rounded-full shadow-2xl dark:shadow-green-800"
          src="/image-home/header1.jpg" // Route of the image file
          height={50} // Desired size with correct aspect ratio
          width={1200} // Desired size with correct aspect ratio
          alt="Homeo"
        />
        <div className="footermenu">
        <h2 className="text-2xl font-extrabold dark:text-white">
        <p> &ensp; &ensp;</p>
{/* Buttons - Menue -Start */}

        <div>
        <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link  href="/">Home</Link>
          </button>    

          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/medicines">Homeo Medicines</Link>
          </button>

          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/about">About</Link>
          </button>
          <button type="button" className="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 shadow-lg shadow-lime-500/50 dark:shadow-lg dark:shadow-lime-800/80 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2">
            <Link href="/contact">Contact</Link>
          </button>
        </div>
{/* Buttons - Menue -End */}


            <p> &ensp; &ensp;</p>
        </h2>
      </div>
      </body>
    </html>
  )
}